# Generated by Django 4.0.10 on 2023-04-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
