# Generated by Django 4.0.10 on 2023-05-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_course_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
