# Generated by Django 4.0.10 on 2023-05-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_pricing_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
