# Generated by Django 4.0.10 on 2023-06-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_course_options_course_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pricing_tiers',
            field=models.ManyToManyField(blank=True, to='content.pricing'),
        ),
    ]
