# Generated by Django 4.0.10 on 2023-08-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_course_pricing_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='currency',
            field=models.CharField(default='usd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=17, max_digits=5),
            preserve_default=False,
        ),
    ]
