# Generated by Django 4.0.10 on 2023-08-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_pricing_currency_pricing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
